export const ENV_VARIABLES = {
    MRKT_ID: "NEXT_PUBLIC_ORDERCLOUD_MARKETPLACE_ID",
    MRKT_NAME: "NEXT_PUBLIC_ORDERCLOUD_MARKETPLACE_NAME",
    MRKT_API_CLIENT: "NEXT_PUBLIC_ORDERCLOUD_CLIENT_ID",
    PROVIDER: "COMMERCE_PROVIDER"
}

export const NEW_PROJECT_CODE = "NEW";