export const ENV_VARIABLES = {
    MRKT_ID: "NEXT_PUBLIC_ORDERCLOUD_MARKETPLACE_ID",
    MRKT_NAME: "NEXT_PUBLIC_ORDERCLOUD_MARKETPLACE_NAME",
    MRKT_API_CLIENT: "NEXT_PUBLIC_ORDERCLOUD_CLIENT_ID",
    MRKT_CLIENT_SECRET: "NEXT_PUBLIC_ORDERCLOUD_CLIENT_SECRET",
    PROVIDER: "COMMERCE_PROVIDER"
}

export const NEW_PROJECT_CODE = "NEW";

export const COSMOS_CONFIGURATION_CONTAINER = "vercelintegrationconfigurations"

export const API_CLIENT_NAME = "Buyer Middleware";